# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Calculate = channel.unary_unary(
        '/Calculator/Calculate',
        request_serializer=calculator__pb2.BinaryOperation.SerializeToString,
        response_deserializer=calculator__pb2.CalculationResult.FromString,
        )
    self.CalculateComplex = channel.unary_unary(
        '/Calculator/CalculateComplex',
        request_serializer=calculator__pb2.ComplexOperation.SerializeToString,
        response_deserializer=calculator__pb2.ComplexResult.FromString,
        )


class CalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Calculate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CalculateComplex(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Calculate': grpc.unary_unary_rpc_method_handler(
          servicer.Calculate,
          request_deserializer=calculator__pb2.BinaryOperation.FromString,
          response_serializer=calculator__pb2.CalculationResult.SerializeToString,
      ),
      'CalculateComplex': grpc.unary_unary_rpc_method_handler(
          servicer.CalculateComplex,
          request_deserializer=calculator__pb2.ComplexOperation.FromString,
          response_serializer=calculator__pb2.ComplexResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
